name: Format (PHP)

on:
  push:
    paths:
      - '**.php'
      - 'composer.lock'
      - '.github/workflows/format_php.yml'
      - 'phpcs.xml'
      - '.phpcs/IxDFCodingStandard/ruleset.xml'
      - '.php-cs-fixer.php'

jobs:
  format_php:
    name: Format PHP
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: bcmath, curl, dom, filter, gd, hash, intl, json, libxml, mbstring, openssl, pdo_mysql, pdo, redis, simpleXML # keep in sync with composer.json
          coverage: none
          tools: cs2pr
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache composer dependencies
        uses: actions/cache@v2
        id: composer-cache
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true' # run composer install only when actions/cache haven't restored cached /vendor dir
        run: composer install -q --no-interaction --no-scripts --no-progress --prefer-dist --no-ansi

      - name: Detect PHP coding style issues
        id: lint_php
        run: composer php:lint
        continue-on-error: true

      - name: Fix detected PHP coding style issues (if any)
        if: ${{ steps.lint_php.outcome == 'failure' }}
        id: fix_php
        run: composer php:fix
        continue-on-error: true

      - name: Commit PHP code-style fixes (if any)
        if: ${{ steps.lint_php.outcome == 'failure' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "#15000 🪄️ Apply coding style fixes to PHP"
          push_options: --force

      - name: Lint PHP coding style issues (if previously detected)
        if: ${{ steps.lint_php.outcome == 'failure' }}
        run: composer phpcs -- --report-full --report-checkstyle=./phpcs-report.xml

      - name: Show PHPCS results in on GitHub UI
        if: ${{ steps.lint_php.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml

      - name: Detect code duplicates in PHP code
        if: ${{ always() }}
        run: ./bin/phpcpd.sh
